apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kalki
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - deployment-backend.yaml
  - deployment-retention.yaml
  - deployment-admin-web.yaml
  - service-backend.yaml
  - service-admin-web.yaml
  - ingress.yaml
  - hpa-backend.yaml
  - jobs/migrate.yaml
  - networkpolicy.yaml
  - pdb.yaml
