---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: schat-backend
  namespace: flux-system
spec:
  image: docker.io/saurav7055/schat-backend
  interval: 2m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: schat-admin-web
  namespace: flux-system
spec:
  image: docker.io/saurav7055/schat-admin-web
  interval: 2m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: schat-retention
  namespace: flux-system
spec:
  image: docker.io/saurav7055/schat-retention
  interval: 2m
