include: package:lints/recommended.yaml

analyzer:
  errors:
    missing_required_argument: error
    must_call_super: error

linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
    unawaited_futures: true
    use_super_parameters: true
